FROM openjdk:15-alpine AS wiremock
EXPOSE 8080

LABEL description="WireMock" \
  maintainer="lesniakwojciech@gmail.com"

ENV WIREMOCK_VERSION="2.26.3"

RUN cd /opt \
  && mkdir wiremock \
  && cd wiremock \
  && wget --quiet https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/$WIREMOCK_VERSION/wiremock-jre8-standalone-$WIREMOCK_VERSION.jar \
  && echo -e '#!/bin/sh\n\
\n\
cat << "DOC"\n\
usage:\n\
\n\
// create new mock\n\
await fetch("http://localhost:8080/__admin/mappings/new", \n\
{\n\
  "method": "POST",\n\
  "body": "\\\n\
{\\\n\
  \"request\": {\\\n\
    \"url\": \"/status\"\\\n\
  },\\\n\
  \"response\": {\\\n\
    \"status\": 200,\\\n\
    \"body\": \"It works!\"\\\n\
  }\\\n\
}\\\n\
"\n\
}\n\
);\n\
\n\
// save mock to configuration\n\
await fetch("http://localhost:8080/__admin/mappings/save", \n\
{\n\
  "method": "POST"\n\
}\n\
);\n\
\n\
// reset configuration\n\
await fetch("http://localhost:8080/__admin/mappings/reset", \n\
{\n\
  "method": "POST"\n\
}\n\
);\n\
\n\
DOC\
' > man \
  && chmod +x man \
  && echo -e '#!/bin/sh\n\
\n\
[ ! -d /opt/wiremock/configuration/mappings ] \\\n\
&& mkdir /opt/wiremock/configuration/mappings \\\n\
&& cat > /opt/wiremock/configuration/mappings/example.json << "DOC"\n\
{\n\
  "mappings": [\n\
    {\n\
      "request": {\n\
        "url": "/status"\n\
      },\n\
      "response": {\n\
        "status": 200,\n\
        "body": "It works!"\n\
      }\n\
    }\n\
  ]\n\
}\n\
DOC\n\
java -jar /opt/wiremock/wiremock-jre8-standalone-$WIREMOCK_VERSION.jar\
' > run \
  && chmod +x run \
  && mkdir --parents configuration/mappings

WORKDIR /opt/wiremock/configuration
CMD ["/opt/wiremock/run"]